name: pharmadeal
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^9.1.0
  dio: ^5.5.0+1
  dio_smart_retry: ^6.0.0
  duration: ^3.0.13
  flash: ^3.1.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.19.0
  otpless_flutter: 2.1.6
  path_provider: ^2.1.4
  platform_info: ^4.0.2
  responsive_framework: ^1.4.0
  riverpod_annotation: ^2.3.5
  talker_dio_logger: ^4.4.0
  talker_flutter: ^4.1.2
  velocity_x: ^4.2.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  riverpod_test: ^0.1.6
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
