// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1294qRZCuIYtVv7dvjW8p-163ORPNjKg',
    appId: '1:900157190561:web:3ed5873a00c0b23db61be0',
    messagingSenderId: '900157190561',
    projectId: 'pharmadeal-app',
    authDomain: 'pharmadeal-app.firebaseapp.com',
    storageBucket: 'pharmadeal-app.appspot.com',
    measurementId: 'G-Q9YTFB34RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQOn3y6V6xD7KWK8EZMPgZtS2jDGmBUQU',
    appId: '1:900157190561:android:eeb3a8102d4b662eb61be0',
    messagingSenderId: '900157190561',
    projectId: 'pharmadeal-app',
    storageBucket: 'pharmadeal-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFFZ9ro-ly9FK4nKYZ6mnNNk2i2wGuO_w',
    appId: '1:900157190561:ios:7173094f255d933db61be0',
    messagingSenderId: '900157190561',
    projectId: 'pharmadeal-app',
    storageBucket: 'pharmadeal-app.appspot.com',
    iosBundleId: 'com.govind.medicine.pharmadeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFFZ9ro-ly9FK4nKYZ6mnNNk2i2wGuO_w',
    appId: '1:900157190561:ios:7173094f255d933db61be0',
    messagingSenderId: '900157190561',
    projectId: 'pharmadeal-app',
    storageBucket: 'pharmadeal-app.appspot.com',
    iosBundleId: 'com.govind.medicine.pharmadeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1294qRZCuIYtVv7dvjW8p-163ORPNjKg',
    appId: '1:900157190561:web:c29b8971a7bab732b61be0',
    messagingSenderId: '900157190561',
    projectId: 'pharmadeal-app',
    authDomain: 'pharmadeal-app.firebaseapp.com',
    storageBucket: 'pharmadeal-app.appspot.com',
    measurementId: 'G-B1HSGKQJJJ',
  );
}
